#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-to-package
spec:
  params:
  - default: ""
    name: ca_cert_data
  - name: maven_repository_url
    value: https://repo.maven.apache.org/maven2
  - default: test
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - name: gitops_user_email
    default: supplychain@cluster.local
  - name: gitops_ssh_secret
    default: #@ data.values.supply_chains.shared.gitops.ssh_secret
  - name: gitops_server_address
    default: #@ data.values.supply_chains.shared.gitops.server_address
  - name: gitops_repository_owner
    default: #@ data.values.supply_chains.shared.gitops.repository_owner
  - name: gitops_repository_name
    default: #@ data.values.supply_chains.shared.gitops.repository_name
  - name: gitops_commit_message
    default: #@ data.values.supply_chains.shared.gitops.commit_message
  - name: gitops_server_kind
    default: #@ data.values.supply_chains.shared.gitops.pull_request.server_kind
  - name: gitops_commit_branch
    default: #@ data.values.supply_chains.shared.gitops.pull_request.commit_branch
  - name: gitops_pull_request_title
    default: #@ data.values.supply_chains.shared.gitops.pull_request.pull_request_title
  - name: gitops_pull_request_body
    default: #@ data.values.supply_chains.shared.gitops.pull_request.pull_request_body
  - name: image_scanning_service_account_publisher
    value: default
  - default: default
    name: image_scanning_service_account_scanner
  - name: image_scanning_cli
    value:
      image: #@ data.values.supply_chains.shared.image_scanning_cli
  - default: 4Gi
    name: image_scanning_workspace_size
  - name: image_scanning_active_keychains
    value: []
  - name: registry
    default:
      ca_cert_data: ""
      repository: #@ data.values.supply_chains.shared.registry.repository
      server: #@ data.values.supply_chains.shared.registry.server
  - name: carvel_package_name_suffix
    default: #@ data.values.supply_chains.shared.carvel_package_name_suffix
  resources:
  - name: source-provider
    params:
    - default: default
      name: serviceAccount
    - default: go-git
      name: gitImplementation
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: source-tester
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      options:
      - name: testing-pipeline
        selector:
          matchExpressions:
            - key: apps.tanzu.vmware.com/has-tests
              operator: Exists
      - passThrough: source
        selector:
          matchExpressions:
            - key: apps.tanzu.vmware.com/has-tests 
              operator: DoesNotExist
  - name: image-provider
    params:
    - default: default
      name: serviceAccount
    - default: default
      name: clusterBuilder
    - default: ./Dockerfile
      name: dockerfile
    - default: ./
      name: docker_build_context
    - default: []
      name: docker_build_extra_args
    sources:
    - name: source
      resource: source-tester
    templateRef:
      kind: ClusterImageTemplate
      options:
      - name: kpack-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: DoesNotExist
      - name: kaniko-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: Exists
  - images:
    - name: image
      resource: image-provider
    name: image-scanner
    params:
    - default: scan-policy
      name: scanning_image_policy
    - default: private-image-scan-template
      name: scanning_image_template
    templateRef:
      kind: ClusterImageTemplate
      options:
      - name: image-scanner-template
        selector:
          matchExpressions:
            - key: apps.tanzu.vmware.com/has-tests
              operator: Exists
      - passThrough: image
        selector:
          matchExpressions:
            - key: apps.tanzu.vmware.com/has-tests 
              operator: DoesNotExist
  - images:
    - name: image
      resource: image-scanner
    name: config-provider
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      options:
      - name: config-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: web
      - name: server-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: server
      - name: worker-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: worker
  - configs:
    - name: app_def
      resource: app-config
    name: service-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: service-bindings
  - configs:
    - name: app_def
      resource: service-bindings
    name: api-descriptors
    templateRef:
      kind: ClusterConfigTemplate
      name: api-descriptors
  - name: carvel-package
    templateRef:
      kind: ClusterConfigTemplate
      name: carvel-package
    params:
      - name: carvel_package_openapiv3_enabled
        value: true
    configs:
      - resource: api-descriptors
        name: config
  - configs:
    - name: config
      resource: carvel-package
    name: package-config-writer
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterTemplate
      name: package-config-writer-and-pull-requester-template
  selector:
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
  selectorMatchExpressions:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values:
    - web
    - server
    - worker