#@ load("@ytt:data", "data")
---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: modern-app-arch-spring-cloud-workshop
spec:
  title: Modern App Architectures with Spring Cloud
  description: A workshop on how to mitigate the challenges of a typical microservices application with the Spring Framework ecosystem
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 60m
  url: https://github.com/timosalm/modern-app-arch-spring-cloud-workshop
  workshop:
    image: ghcr.io/timosalm/modern-app-arch-spring-cloud-workshop@sha256:e110faf754ebc8be805ba2aad6cea2692b3da7ac65cf68f659948a6b3de4d845
    files:
    - git:
        url: https://github.com/timosalm/modern-app-arch-spring-cloud-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
      - /samples/**
  session:
    namespaces:
      budget: custom
      role: view
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      git:
        enabled: true
      registry:
        enabled: true
      examiner:
        enabled: true
      files:
        enabled: true
    env: 
    - name: TAP_INGRESS
      value: #@ data.values.tap.ingress_domain
    ingresses:
    - name: twelve-factors
      protocol: https
      host: 12factor.net 
      port: 443
    objects: []