---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-std-installer-sa
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-std-install-cluster-admin
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-std-install-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-std-install-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tanzu-std-installer-sa
    namespace: tkg-system
