apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-config-features-overlay-secret
  namespace: tap-install
stringData:
  config-features-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "config-features", "namespace": "knative-serving"}}), expects="1+"
    ---
    data:
      #@overlay/match missing_ok=True
      kubernetes.containerspec-addcapabilities: "enabled"
      #@overlay/match missing_ok=True
      kubernetes.podspec-securitycontext: "enabled"
      #@overlay/match missing_ok=True
      kubernetes.podspec-persistent-volume-claim: "enabled"
      #@overlay/match missing_ok=True
      kubernetes.podspec-persistent-volume-write: "enabled"
      #@overlay/match missing_ok=True
      kubernetes.podspec-fieldref: "enabled"
      