apiVersion: v1
kind: Secret
metadata:
  name: flux-source-controller-overlay-secret
  namespace: tap-install
stringData:
  scm-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "source-controller-manager"}}), expects="1+"
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by=overlay.subset({"name":"manager"})
          - name: manager
            resources:
              limits:
                cpu: 2000m
                memory: 2Gi