#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: workshops
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workshops
  namespace: workshops
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.2: "upsert after upserting eso/workshops-sensitive-values"
    kapp.k14s.io/change-rule.3: "delete before deleting pkgi"
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: #@ data.values.workshops.git.url
        ref: #@ data.values.workshops.git.ref
        subPath: #@ data.values.workshops.git.sub_path
  template:
  - ytt: 
      valuesFrom:
      - configMapRef:
          name: workshops-values
      - secretRef:
          name: workshops-sensitive-values
  deploy:
  - kapp: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workshops-syncer
  namespace: workshops
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshops-syncer-default
  namespace: workshops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workshops-syncer
subjects:
  - kind: ServiceAccount
    name: default
    namespace: workshops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshops-syncer-cr
rules:
- apiGroups:
  - training.educates.dev
  resources:
  - workshops
  - trainingportals
  verbs:
  - '*'
- apiGroups:
  - carto.run
  resources:
  - clusterimagetemplates
  - clustertemplates
  - clustersupplychains
  verbs:
  - '*'  
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - accelerators
  verbs:
  - '*' 
- apiGroups:
  - apis.apps.tanzu.vmware.com
  resources:
  - apidescriptors
  verbs:
  - '*'   
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshops-syncer-cr-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshops-syncer-cr
subjects:
  - kind: ServiceAccount
    name: default
    namespace: workshops
