#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workshops-values
  namespace: workshops
data:
  values.yaml: #@ yaml.encode(data.values.workshops.values)