#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: application-configuration-service
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
    kapp.k14s.io/change-rule.eso.1: "upsert after upserting eso/tap-sensitive-values"
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: application-configuration-service.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.tap_install.packages.acs.version.package_version