#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: full-deps-package-repo
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: #@ "{}:{}".format(data.values.tap_install.tap_package_repository.oci_tbs_deps_repository, data.values.tap_install.version.package_repo_bundle_tag)