#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: full-deps-values
  namespace: tap-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    kp_default_repository: "(@= data.values.tap_install.values.buildservice.kp_default_repository @)"