#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: tdp-app-image-overlay-secret
  namespace: tap-install
stringData:
  #@ if hasattr(data.values.tdp_configurator, "custom_image"):
  tdp-app-image-overlay.yaml: #@ data.values.tdp_configurator.overlay.replace('IMAGE-REFERENCE', data.values.tdp_configurator.custom_image) 
  #@ else:
  tdp-app-image-overlay.yaml: {}
  #@ end