#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: tdp-app-image-overlay-secret
  namespace: tap-install
stringData:
  tdp-app-image-overlay.yaml: #@ data.values.tdp_overlay.replace('IMAGE-REFERENCE', data.values.tdp_configurator.custom_image) 
---
#@data/values-schema
---
tdp_overlay: |
  #@ load("@ytt:overlay", "overlay")
  #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "server", "namespace": "tap-gui"}}), expects="1+"
  ---
  spec:
    template:
      spec:
        containers:
          #@overlay/match by=overlay.subset({"name": "backstage"}),expects="1+"
          #@overlay/match-child-defaults missing_ok=True
          - image: IMAGE-REFERENCE
          #@overlay/replace
            args:
            - -c
            - |
              export KUBERNETES_SERVICE_ACCOUNT_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
              exec /layers/tanzu-buildpacks_node-engine-lite/node/bin/node portal/dist/packages/backend  \
              --config=portal/app-config.yaml \
              --config=portal/runtime-config.yaml \
              --config=/etc/app-config/app-config.yaml