#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-sensitive-values
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-group: eso/tap-sensitive-values
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore"
spec:
  secretStoreRef:
    name: tanzu-standard-secrets
    kind: SecretStore
  refreshInterval: "1m"
  data:
    - secretKey: sensitive-harbor-values.yaml
      remoteRef: #@ data.values.tap_install.secrets.eso.remote_refs.harbor_sensitive_values.sensitive_harbor_values_yaml
