tap_std:
  harbor_install:
    values:
      namespace: tanzu-system-registry
      #! The FQDN for accessing Harbor admin UI and Registry service.
      hostname: harbor.main.emea.end2end.link
      #! The network port of the Envoy service in Contour or other Ingress Controller.
      port:
        https: 443
      #! The log level of core, exporter, jobservice, registry. Its value is debug, info, warning, error or fatal.
      logLevel: info
      tlsCertificate:
        #! [Required] the certificate
        tls.crt: IRRELEVANT
        #! [Required] the private key
        tls.key: IRRELEVANT
        ca.crt: |
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
          MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
          DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
          AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
          ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
          wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
          LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
          4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
          bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
          sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
          Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
          FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
          SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
          PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
          TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
          SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
          c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
          +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
          ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
          b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
          U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
          MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
          5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
          9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
          WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
          he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
          Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
          -----END CERTIFICATE-----
      #! [Optional] The name of the secret for harbor FQDN if you want to use your own TLS certificate,
      #! which contains keys named:
      #! "tls.crt" - the certificate
      #! "tls.key" - the private key
      #! We will issue the certificate by cert-manager when it's empty and the tlsCertificate is empty.
      tlsCertificateSecretName: 
      #! Use contour http proxy instead of the ingress when it's true
      enableContourHttpProxy: true
      #! [Optional] Set http proxy timeout policy
      contourHttpProxy:
        #! [Optional] Timeout for receiving a response from the server after processing a request from client.
        #! the value assigned to timeout should be a number followed by a letter like "h", "m", "s", or "ms", i.e. 1h, 5m, 60s, 1000ms; or infinite or infinity.
        timeout: 30m
        #! [Optional] Timeout for how long the proxy should wait while there is no activity during single request/response (for HTTP/1.1) or stream (for HTTP/2).
        #! the value assigned to idleTimeout should also be a number followed by a letter like "h", "m", "s", or "ms", i.e. 1h, 5m, 60s, 1000ms; or infinite or infinity.
        idleTimeout: 30m
      #! [Required] The initial password of Harbor admin.
      harborAdminPassword: # External secret
      #! [Required] The secret key used for encryption. Must be a string of 16 chars.
      secretKey: # External secret
      database:
        #! [Required] The initial password of the postgres database.
        password: # External secret
        shmSizeLimit:
        maxIdleConns:
        maxOpenConns:
      exporter:
        cacheDuration:
      core:
        replicas: 2
        #! [Required] Secret is used when core server communicates with other components.
        secret: # External secret
        #! [Required] The XSRF key. Must be a string of 32 chars.
        xsrfKey: # External secret
      jobservice:
        replicas: 1
        #! [Required] Secret is used when job service communicates with other components.
        secret: # External secret
      registry:
        replicas: 1
        #! [Required] Secret is used to secure the upload state from client
        #! and registry storage backend.
        #! See: https://github.com/docker/distribution/blob/master/docs/configuration.md#http
        secret: # External secret
      notary:
        #! Whether to install Notary
        enabled: true
      trivy:
        #! enabled the flag to enable Trivy scanner
        enabled: true
        replicas: 1
        #! gitHubToken the GitHub access token to download Trivy DB
        gitHubToken: ""
        #! skipUpdate the flag to disable Trivy DB downloads from GitHub
        #!
        #! You might want to set the value of this flag to `true` in test or CI/CD environments to avoid GitHub rate limiting issues.
        #! If the value is set to `true` you have to manually download the `trivy.db` file and mount it in the
        #! `/home/scanner/.cache/trivy/db/trivy.db` path.
        skipUpdate: false
        #! The offlineScan option prevents Trivy from sending API requests to identify dependencies.
        #!
        #! Scanning JAR files and pom.xml may require Internet access for better detection, but this option tries to avoid it.
        #! For example, the offline mode will not try to resolve transitive dependencies in pom.xml when the dependency doesn't
        #! exist in the local repositories. It means a number of detected vulnerabilities might be fewer in offline mode.
        #! It would work if all the dependencies are in local.
        #! This option doesn’t affect DB download. You need to specify skipUpdate as well as offlineScan in an air-gapped environment.
        offlineScan: false
        #! the timeout set for trivy scanner, it should be a number followed by a letter like "h", "m", "s", or "ms", i.e. 1h, 5m, 60s, 1000ms
        timeout:
      #! The persistence is always enabled and a default StorageClass
      #! is needed in the k8s cluster to provision volumes dynamically.
      #! Specify another StorageClass in the "storageClass" or set "existingClaim"
      #! if you have already existing persistent volumes to use
      #!
      #! For storing images and charts, you can also use "azure", "gcs", "s3",
      #! "swift" or "oss". Set it in the "imageChartStorage" section
      persistence:
        persistentVolumeClaim:
          registry:
            #! Use the existing PVC which must be created manually before bound,
            #! and specify the "subPath" if the PVC is shared with other components
            existingClaim: ""
            #! Specify the "storageClass" used to provision the volume. Or the default
            #! StorageClass will be used(the default).
            #! Set it to "-" to disable dynamic provisioning
            storageClass: ""
            subPath: ""
            accessMode: ReadWriteOnce
            size: 200Gi
          jobservice:
            jobLog:
              existingClaim: ""
              storageClass: ""
              subPath: ""
              accessMode: ReadWriteOnce
              size: 1Gi
          database:
            existingClaim: ""
            storageClass: ""
            subPath: ""
            accessMode: ReadWriteOnce
            size: 20Gi
          redis:
            existingClaim: ""
            storageClass: ""
            subPath: ""
            accessMode: ReadWriteOnce
            size: 1Gi
          trivy:
            existingClaim: ""
            storageClass: ""
            subPath: ""
            accessMode: ReadWriteOnce
            size: 5Gi
        #! Define which storage backend is used for registry and chartmuseum to store
        #! images and charts. Refer to
        #! https://github.com/docker/distribution/blob/master/docs/configuration.md#storage
        #! for the detail.
        imageChartStorage:
          #! Specify whether to disable `redirect` for images and chart storage, for
          #! backends which not supported it (such as using minio for `s3` storage type), please disable
          #! it. To disable redirects, simply set `disableredirect` to `true` instead.
          #! Refer to
          #! https://github.com/docker/distribution/blob/master/docs/configuration.md#redirect
          #! for the detail.
          disableredirect: false
          #! Specify the type of storage: "filesystem", "azure", "gcs", "s3", "swift",
          #! "oss" and fill the information needed in the corresponding section. The type
          #! must be "filesystem" if you want to use persistent volumes for registry
          #! and chartmuseum
          type: filesystem
          filesystem:
            rootdirectory: /storage
          azure:
            accountname: accountname #! required
            accountkey: base64encodedaccountkey #! required
            container: containername #! required
            realm: core.windows.net #! optional
          gcs:
            bucket: bucketname #! required
            #! The base64 encoded json file which contains the key
            encodedkey: base64-encoded-json-key-file #! optional
            rootdirectory: null #! optional
            chunksize: 5242880 #! optional
          s3:
            region: us-west-1 #! required
            bucket: bucketname #! required
            accesskey: null #! eg, awsaccesskey
            secretkey: null #! eg, awssecretkey
            regionendpoint: null #! optional, eg, http://myobjects.local
            encrypt: false #! optional
            keyid: null #! eg, mykeyid
            secure: true #! optional
            skipverify: false #! optional
            v4auth: true #! optional
            chunksize: null #! optional
            rootdirectory: null #! optional
            storageclass: STANDARD #! optional
            multipartcopychunksize: null #! optional
            multipartcopymaxconcurrency: null #! optional
            multipartcopythresholdsize: null #! optional
          swift:
            authurl: https://storage.myprovider.com/v3/auth
            username: username
            password: password
            container: containername
            region: null #! eg, fr
            tenant: null #! eg, tenantname
            tenantid: null #! eg, tenantid
            domain: null #! eg, domainname
            domainid: null #! eg, domainid
            trustid: null #! eg, trustid
            insecureskipverify: null #! bool eg, false
            chunksize: null #! eg, 5M
            prefix: null #! eg
            secretkey: null #! eg, secretkey
            accesskey: null #! eg, accesskey
            authversion: null #! eg, 3
            endpointtype: null #! eg, public
            tempurlcontainerkey: null #! eg, false
            tempurlmethods: null #! eg
          oss:
            accesskeyid: accesskeyid
            accesskeysecret: accesskeysecret
            region: regionname
            bucket: bucketname
            endpoint: null #! eg, endpoint
            internal: null #! eg, false
            encrypt: null #! eg, false
            secure: null #! eg, true
            chunksize: null #! eg, 10M
            rootdirectory: null #! eg, rootdirectory
      #! The http/https network proxy for core, exporter, jobservice, trivy
      proxy:
        httpProxy:
        httpsProxy:
        noProxy: 127.0.0.1,localhost,.local,.internal
      #! The PSP names used by Harbor pods. The names are separated by ','. 'null' means all PSP can be used.
      pspNames: null
      #! The custom ca bundle secret, the secret must contain key named "ca.crt"
      #! which will be injected into the trust store for core, jobservice, registry, trivy components
      caBundleSecretName: ""
      #! The metrics used by core, registry and exporter
      metrics:
        enabled: false
        core:
          path: /metrics
          port: 8001
        registry:
          path: /metrics
          port: 8001
        jobservice:
          path: /metrics
          port: 8001
        exporter:
          path: /metrics
          port: 8001
      #! Default [] is equivalent to have both ["IPv4","IPv6"]. Or you can choose one of ["IPv4"] or ["IPv6"]
      network:
        ipFamilies: []
      #! tracing configuration for Harbor
      trace:
        enabled: false
        #! trace provider: jaeger or otel
        #! jaeger should be 1.26+
        provider: jaeger
        #! set sample_rate to 1.0 if you wanna sampling 100% of trace data; set 0.5 if you wanna sampling 50% of trace data, and so forth
        sample_rate: 1.0
        #! namespace used to differentiate different harbor services
        namespace:
        #! attributes is a key value dict contains user defined attributes used to initialize trace provider
        attributes:
          application: harbor
        jaeger:
          #! jaeger supports two modes:
          #!   collector mode(set endpoint and optionally set username, password if needed)
          #!   agent mode(only set both agent_host and agent_port)
          #! endpoint example - endpoint: http://hostname:14268/api/traces
          endpoint: http://hostname:14268/api/traces
          username:
          password:
          #! agent_host example - agent_host: hostname
          agent_host:
          #! export trace data by jaeger.thrift in compact mode, agent_port example as below:
          #! agent_port example - agent_port: 6831
          agent_port:
        otel:
          endpoint: hostname:4318
          url_path: /v1/traces
          compression: false
          insecure: true
          #! timeout: an integer represents the max waiting time for the backend to process each spans batch, in seconds
          timeout: 10
      #! cache layer configurations
      #! if this feature enabled, harbor will cache the resource
      #! `project/project_metadata/repository/artifact/manifest` in the redis
      #! which help to improve the performance of high concurrent pulling manifest.
      cache:
        #! default is not enabled.
        enabled: false
        #! default keep cache for one day.
        expireHours: 24
