tap_std:
  externaldns_install:
    hosted_zone_id: Z04147751VKC48IKUQS06
    role: arn:aws:iam::377668981663:role/EmeaE2EDemoHostedZoneChanger
    values:
      namespace: tanzu-system-registry
      deployment:
        args:
          - --source=service
          - --source=ingress
          - --source=contour-httpproxy
          - #@ "--domain-filter=" + str(data.values.tap_install.values.shared.ingress_domain)
          - --policy=upsert-only
          - --registry=txt
          - #@ "--txt-owner-id=" + str(data.values.tap_std.externaldns_install.hosted_zone_id)
          - --txt-prefix=txt
          - --provider=aws
          - --aws-zone-type=public
          - --aws-prefer-cname
      serviceaccount:
        annotations:
          eks.amazonaws.com/role-arn: #@ data.values.tap_std.externaldns_install.role