tap_install:
  package_repository:
    oci_repository: 377668981663.dkr.ecr.eu-central-1.amazonaws.com/tap-images
  version:
    package_repo_bundle_tag: "1.6.2"
    package_version: "1.6.2"
  packages:
    acs:
      version:
        package_version: "2.1.0"
    scg:
      version:
        package_version: "2.0.6"
