tdp_configurator:
  # aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 377668981663.dkr.ecr.eu-central-1.amazonaws.com && imgpkg describe -b $(kubectl get -n tap-install $(kubectl get package -n tap-install --field-selector spec.refName=tpb.tanzu.vmware.com -o name) -o jsonpath="{.spec.template.spec.fetch[0].imgpkgBundle.image}") -o yaml --tty=true | grep -A 1 "kbld.carvel.dev/id: harbor-repo.vmware.com/esback/configurator" | grep "image: " | sed 's/\simage: //g'
  image: 377668981663.dkr.ecr.eu-central-1.amazonaws.com/tap-images@sha256:001d3879720c2dc131ec95db6c6a34ff3c2f912d9d8b7ffacb8da08a844b740f
  config: |
    app:
      plugins:
        - name: '@timosalm/plugin-tech-insights-wrapper'
          version: '1.0.0'
        - name: '@timosalm/tech-radar-wrapper'
          version: '1.0.1'
        - name: '@timosalm/scaffolder-wrapper'
          version: '1.0.1'
    backend:
      plugins:
        - name: '@timosalm/plugin-tech-insights-wrapper-backend'
          version: '1.0.0'
  custom_image: harbor.main.emea.end2end.link/tap/tdp-config-tdp-configurator@sha256:b3b8824a730576204d2159a68fa0f2e978f8c942d1b3941404343e020dee7e9c