tdp_configurator:
  # aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 377668981663.dkr.ecr.eu-central-1.amazonaws.com && imgpkg describe -b $(kubectl get -n tap-install $(kubectl get package -n tap-install --field-selector spec.refName=tpb.tanzu.vmware.com -o name) -o jsonpath="{.spec.template.spec.fetch[0].imgpkgBundle.image}") -o yaml --tty=true | grep -A 1 "kbld.carvel.dev/id: harbor-repo.vmware.com/esback/configurator" | grep "image: " | sed 's/\simage: //g'
  image: 377668981663.dkr.ecr.eu-central-1.amazonaws.com/tap-images@sha256:001d3879720c2dc131ec95db6c6a34ff3c2f912d9d8b7ffacb8da08a844b740f
  config: |
    app:
      plugins:
        - name: '@timosalm/plugin-tech-insights-wrapper'
          version: '1.0.0'
    backend:
      plugins:
        - name: '@timosalm/plugin-tech-insights-wrapper-backend'
          version: '1.0.0'
  custom_image: harbor.main.emea.end2end.link/tap/tdp-configurator-tdp-configurator@sha256:472be411ef7b4fb023254baf6cbdfa8e8cd9ae914e3c34215f2e72253823337a
  overlay: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "server", "namespace": "tap-gui"}}), expects="1+"
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by=overlay.subset({"name": "backstage"}),expects="1+"
            #@overlay/match-child-defaults missing_ok=True
            - image: IMAGE-REFERENCE
            #@overlay/replace
              args:
              - -c
              - |
                export KUBERNETES_SERVICE_ACCOUNT_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
                exec /layers/tanzu-buildpacks_node-engine-lite/node/bin/node portal/dist/packages/backend  \
                --config=portal/app-config.yaml \
                --config=portal/runtime-config.yaml \
                --config=/etc/app-config/app-config.yaml