workshops:
  git:
    url: https://github.com/timosalm/tap-gitops-workshops
    ref: educates
    sub_path:
  values:
    tap:
      ingress_domain: main.emea.end2end.link
      ingress_wildcard_cert: tanzu-system-ingress/contour-tls-delegation-cert
      product_docs_base_url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap
    container_registry:
      hostname: harbor.main.emea.end2end.link
      repository: tap-workshop-examples
      username: "" # External secret
      password: "" # External secret
    training_portal:
      adminPassword: "" # External secret
      robotPassword: "" # External secret
      robotClientId: "" # External secret
      robotClientSecret: "" # External secret
    metadatastore:
      accesstoken: "" # External secret