workshops:
  git:
    url: https://github.com/timosalm/tap-gitops-workshops
    ref: educates
    sub_path:
  values:
    tap:
      ingress_domain: main.emea.end2end.link
      ingress_wildcard_cert: tanzu-system-ingress/contour-tls-delegation-cert
    
  