#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contour-tls-delegation-cert
  namespace: tanzu-system-ingress
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting contour"
    kapp.k14s.io/change-rule.1: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.2: "delete before deleting pkgi"
spec:
  commonName: #@ "*.{}".format(data.values.tap_install.values.shared.ingress_domain)
  dnsNames:
  - #@ "*.{}".format(data.values.tap_install.values.shared.ingress_domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: contour-tls-delegation-cert

