#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore"
    kapp.k14s.io/change-rule.1: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.2: "delete before deleting pkgi"
spec:
  secretStoreRef:
    name: ingress-secrets
    kind: SecretStore
  refreshInterval: "1m"
  data:
    - secretKey: secret-access-key
      remoteRef: 
        key: #@ data.values.tap_install.secrets.eso.remote_refs.ingress_sensitive_values.sensitive_ingress_values.key
        property: secret-access-key
    - secretKey: access-key-id
      remoteRef: 
        key: #@ data.values.tap_install.secrets.eso.remote_refs.ingress_sensitive_values.sensitive_ingress_values.key
        property: access-key-id