apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: tanzu-system-ingress
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting contour"
    kapp.k14s.io/change-rule.1: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.2: "delete before deleting pkgi"
spec:
  delegations:
    - secretName: contour-tls-delegation-cert
      targetNamespaces:
        - "*"