#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: tkg-system
stringData:
  values.yaml: #@ yaml.encode(data.values.tap_std.externaldns_install.values)