#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
spec:
  packageRef:
    refName:  external-dns.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.tap_std.version.externaldns_package_version
  serviceAccountName: tanzu-std-installer-sa
  values:
  - secretRef:
      name: external-dns-values