#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: educates-cluster-essentials
  namespace: educates-package
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: educates-cluster-essentials-overlay-secret
spec:
  packageRef:
    refName: cluster-essentials.educates.dev
    versionSelection:
      constraints: #@ data.values.educates.version.package_repo_bundle_tag
  serviceAccountName: educates-installer-sa
  values:
  - secretRef:
      name: educates-cluster-essentials-values