#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: educates-training-platform
  namespace: educates-package
spec:
  packageRef:
    refName: training-platform.educates.dev
    versionSelection:
      constraints: #@ data.values.educates.version.package_repo_bundle_tag
  serviceAccountName: educates-installer-sa
  values:
  - secretRef:
      name: educates-training-platform-values