apiVersion: v1
kind: Secret
metadata:
  name: educates-cluster-essentials-overlay-secret
  namespace: educates-package
stringData:
  sc-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "kyverno", "namespace": "kyverno"}})
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by=overlay.subset({"name":"kyverno"})
          - name: kyverno
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 128Mi