#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: educates-training-platform-values
  namespace: educates-package
stringData:
  values.yaml: #@ yaml.encode(data.values.educates.educates_training_platform)